language: python

before_script:
- pip install tox

# test script
script:  tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django17
    - python: 2.7
      env: TOXENV=py27-django18
    - python: 2.7
      env: TOXENV=py27-django19
    - python: 3.4
      env: TOXENV=py34-django17
    - python: 3.4
      env: TOXENV=py34-django18
    - python: 3.4
      env: TOXENV=py34-django19
    - python: 3.5
      env: TOXENV=py35-django17
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: pypy
      env: TOXENV=pypy-django17
    - python: pypy
      env: TOXENV=pypy-django18
    - python: pypy
      env: TOXENV=pypy-django19
    - python: 3.5-dev
      env: TOXENV=pydev-django17
    - python: 3.5-dev
      env: TOXENV=pydev-django18
    - python: 3.5-dev
      env: TOXENV=pydev-django19
    - python: nightly
      env: TOXENV=pyovernight-django17
    - python: nightly
      env: TOXENV=pyovernight-django18
    - python: nightly
      env: TOXENV=pyovernight-django19
    - python: 3.5
      env: TOXENV=lint
    - python: 3.5
      env: TOXENV=coverage
  fast_finish: true
  allow_failures:
    - python: 3.5
      env: TOXENV=lint

sudo: false
