language: python

before_script:
- pip install tox

# test script
script:  tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-17
    - python: 2.7
      env: TOXENV=py27-18
    - python: 2.7
      env: TOXENV=py27-19
    - python: 3.4
      env: TOXENV=py34-17
    - python: 3.4
      env: TOXENV=py34-18
    - python: 3.4
      env: TOXENV=py34-19
    - python: 3.5
      env: TOXENV=py35-17
    - python: 3.5
      env: TOXENV=py35-18
    - python: 3.5
      env: TOXENV=py35-19
    - python: pypy
      env: TOXENV=pypy-17
    - python: pypy
      env: TOXENV=pypy-18
    - python: pypy
      env: TOXENV=pypy-19
    - python: 3.5
      env: TOXENV=lint
    - python: 3.5
      env: TOXENV=coverage
  fast_finish: true
  allow_failures:
    - python: 3.5
      env: TOXENV=lint

sudo: false
