language: python
python: 3.4

before_script:
- pip install tox

# test script
script:  tox

matrix:
  include:
      env: TOXENV=py27-17
      env: TOXENV=py27-18
      env: TOXENV=py27-19
      env: TOXENV=py34-17
      env: TOXENV=py34-18
      env: TOXENV=py34-19
      env: TOXENV=py35-17
      env: TOXENV=py35-18
      env: TOXENV=py35-19
      env: TOXENV=pypy-17
      env: TOXENV=pypy-18
      env: TOXENV=pypy-19
      env: TOXENV=lint
      env: TOXENV=coverage
  fast_finish: true
  allow_failures:
      env: TOXENV=lint

sudo: false
