# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SymmetricalEureka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.AddField(
            model_name='character',
            name='Char_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='Name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
