# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 18:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SymmetricalEureka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caster_class', models.CharField(choices=[('bd', 'Bard'), ('cl', 'Cleric'), ('dr', 'Druid'), ('pd', 'Paladin'), ('rg', 'Ranger'), ('sc', 'Sorcerer'), ('wa', 'Warlock'), ('wi', 'Wizard')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SpellListing',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('page', models.CharField(default='', max_length=10)),
                ('spell_range', models.CharField(default='', max_length=256)),
                ('duration', models.CharField(default='', max_length=256)),
                ('casting_time', models.CharField(default='', max_length=256)),
                ('concentration', models.BooleanField(default=False)),
                ('ritual', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('description', models.TextField(default='')),
                ('material_components', models.TextField(default='')),
                ('components', models.CharField(choices=[('', 'None'), ('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material'), ('VS', 'VS'), ('VM', 'VM'), ('SM', 'SM'), ('VSM', 'VSM')], default='', max_length=3)),
                ('school', models.CharField(choices=[('ab', 'Abjuration'), ('cj', 'Conjuration'), ('dv', 'Divination'), ('en', 'Enchantment'), ('ev', 'Evocation'), ('il', 'Illusion'), ('ne', 'Necromancy'), ('tr', 'Transmutation')], max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='spellclasses',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SymmetricalEureka.SpellListing'),
        ),
    ]
