# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymmetricalEureka', '0002_auto_20170113_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelllisting',
            name='components',
            field=models.CharField(choices=[('', 'None'), ('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material'), ('VS', 'Verbal, Somatic'), ('VM', 'Verbal, Material'), ('SM', 'Somatic, Material'), ('VSM', 'Verbal, Somatic, Material')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='spelllisting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spelllisting',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='spelllisting',
            name='material_components',
            field=models.TextField(blank=True, default=''),
        ),
    ]
