# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SymmetricalEureka', '0004_auto_20170417_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spells',
            field=models.ManyToManyField(to='SymmetricalEureka.SpellListing'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
