# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymmetricalEureka', '0006_auto_20170419_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spells',
            field=models.ManyToManyField(blank=True, to='SymmetricalEureka.SpellListing'),
        ),
    ]
