# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SymmetricalEureka', '0007_auto_20170425_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
